// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWovy4bVuY4PFbUEEO2FlyRh_e_yfSGFY',
    appId: '1:662694883365:web:1527fa727d8cc1a04e4fcc',
    messagingSenderId: '662694883365',
    projectId: 'sherise-36d43',
    authDomain: 'sherise-36d43.firebaseapp.com',
    storageBucket: 'sherise-36d43.firebasestorage.app',
    measurementId: 'G-N5LN57BGRE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpboruQPgem5M2iOVTLi00A9Z_5cDzKoY',
    appId: '1:662694883365:android:b900d24310582bc84e4fcc',
    messagingSenderId: '662694883365',
    projectId: 'sherise-36d43',
    storageBucket: 'sherise-36d43.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM3GoOQeVxJGM6aaBEy0iXepBkSyTRh1E',
    appId: '1:662694883365:ios:db760abc1dd5ed174e4fcc',
    messagingSenderId: '662694883365',
    projectId: 'sherise-36d43',
    storageBucket: 'sherise-36d43.firebasestorage.app',
    iosBundleId: 'com.example.sherise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM3GoOQeVxJGM6aaBEy0iXepBkSyTRh1E',
    appId: '1:662694883365:ios:db760abc1dd5ed174e4fcc',
    messagingSenderId: '662694883365',
    projectId: 'sherise-36d43',
    storageBucket: 'sherise-36d43.firebasestorage.app',
    iosBundleId: 'com.example.sherise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWovy4bVuY4PFbUEEO2FlyRh_e_yfSGFY',
    appId: '1:662694883365:web:c96d95a9c047b2074e4fcc',
    messagingSenderId: '662694883365',
    projectId: 'sherise-36d43',
    authDomain: 'sherise-36d43.firebaseapp.com',
    storageBucket: 'sherise-36d43.firebasestorage.app',
    measurementId: 'G-S0K303MLS2',
  );
}
